/** @deprecated Import from @/lib/rental-catalog */
export {
  RENTAL_UNIT,
  RENTAL_CATEGORY_PREFIX,
  RENTAL_CATEGORY_OPTIONS,
  RENTAL_DEPARTMENTS,
  RENTAL_FAMILIES,
  skuPrefixForCategory,
  isRentalProduct,
  rentalDepartmentFromCategory,
  rentalDepartmentId,
  parseRentalName,
  formatRentalName,
  groupRentalCatalog,
  sortRentalProducts,
  matchesRentalFilter,
  rentalPickerLabel,
  type RentalFilter,
  type RentalDepartmentId,
} from "./rental-catalog";
